version: "2"

# volumes的加载问题
# - /data是匿名volume，使用docker-compose rm -v可以连带容器一起删除
# volumes不要混用，例如mysql是/data/mysql 而不是/data/gogs/mysql
# 必须使用默认bridge，因为drone使用docker版的git拉取镜像，目前无法配置git容器ip，所以全部容器都要用没人bridge
services:

  drone-server:
    image: drone/drone
    restart: unless-stopped
    ports:
      - 8000:8000
    links:
      - gogs
    environment:
      - DRONE_OPEN=true
      - DRONE_GOGS=true
      - DRONE_GOGS_URL=http://gogs:3000
      - DRONE_SECRET=drone
    volumes:
      - /data/drone:/var/lib/drone/
    network_mode: bridge

  drone-agent:
    image: drone/drone
    command: agent
    restart: unless-stopped
    depends_on: [ drone-server ]
    environment:
      - DRONE_SERVER=ws://drone-server:8000/ws/broker
      - DRONE_SECRET=drone
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    network_mode: bridge

  gogs:
    image: gogs/gogs
    restart: unless-stopped
    ports:
      - "3000:3000"
      - "10022:22"
    depends_on:
      - mysql
    links:
      - mysql
    volumes:
      - /data/gogs:/data
    network_mode: bridge

  mysql:
    image: mysql
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=gogs
      - MYSQL_USER=halsn
      - MYSQL_PASSWORD=halsn
    volumes:
      - /data/mysql:/var/lib/mysql
    network_mode: bridge

  sonarqube:
    restart: unless-stopped
    image: sonarqube:alpine
    environment:
      - SONARQUBE_HOME=/opt/sonarqube
      - SONARQUBE_JDBC_USERNAME=sonar
      - SONARQUBE_JDBC_PASSWORD=sonar
      - SONARQUBE_JDBC_URL=
    ports:
      - "9000:9000"
      - "9092:9092"
    volumes:
      - /data/sonarqube/data:/opt/sonarqube/data
      - /data/sonarqube/extensions:/opt/sonarqube/extensions
    network_mode: bridge
